// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DevInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DevInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DevInfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DevInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DevInfo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DevInfo_2eproto;
namespace Flee {
class DevInfo;
struct DevInfoDefaultTypeInternal;
extern DevInfoDefaultTypeInternal _DevInfo_default_instance_;
}  // namespace Flee
PROTOBUF_NAMESPACE_OPEN
template<> ::Flee::DevInfo* Arena::CreateMaybeMessage<::Flee::DevInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Flee {

// ===================================================================

class DevInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Flee.DevInfo) */ {
 public:
  inline DevInfo() : DevInfo(nullptr) {}
  ~DevInfo() override;
  explicit PROTOBUF_CONSTEXPR DevInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DevInfo(const DevInfo& from);
  DevInfo(DevInfo&& from) noexcept
    : DevInfo() {
    *this = ::std::move(from);
  }

  inline DevInfo& operator=(const DevInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline DevInfo& operator=(DevInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DevInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const DevInfo* internal_default_instance() {
    return reinterpret_cast<const DevInfo*>(
               &_DevInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DevInfo& a, DevInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(DevInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DevInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DevInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DevInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DevInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DevInfo& from) {
    DevInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DevInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Flee.DevInfo";
  }
  protected:
  explicit DevInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBootloaderFieldNumber = 1,
    kProcVersionFieldNumber = 2,
    kCodenameFieldNumber = 3,
    kIncrementalFieldNumber = 4,
    kFingerprintFieldNumber = 5,
    kBootIdFieldNumber = 6,
    kAndroidIdFieldNumber = 7,
    kBaseBandFieldNumber = 8,
    kInnerVersionFieldNumber = 9,
  };
  // optional bytes bootloader = 1;
  bool has_bootloader() const;
  private:
  bool _internal_has_bootloader() const;
  public:
  void clear_bootloader();
  const std::string& bootloader() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bootloader(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bootloader();
  PROTOBUF_NODISCARD std::string* release_bootloader();
  void set_allocated_bootloader(std::string* bootloader);
  private:
  const std::string& _internal_bootloader() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bootloader(const std::string& value);
  std::string* _internal_mutable_bootloader();
  public:

  // optional bytes procVersion = 2;
  bool has_procversion() const;
  private:
  bool _internal_has_procversion() const;
  public:
  void clear_procversion();
  const std::string& procversion() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_procversion(ArgT0&& arg0, ArgT... args);
  std::string* mutable_procversion();
  PROTOBUF_NODISCARD std::string* release_procversion();
  void set_allocated_procversion(std::string* procversion);
  private:
  const std::string& _internal_procversion() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_procversion(const std::string& value);
  std::string* _internal_mutable_procversion();
  public:

  // optional bytes codename = 3;
  bool has_codename() const;
  private:
  bool _internal_has_codename() const;
  public:
  void clear_codename();
  const std::string& codename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_codename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_codename();
  PROTOBUF_NODISCARD std::string* release_codename();
  void set_allocated_codename(std::string* codename);
  private:
  const std::string& _internal_codename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_codename(const std::string& value);
  std::string* _internal_mutable_codename();
  public:

  // optional bytes incremental = 4;
  bool has_incremental() const;
  private:
  bool _internal_has_incremental() const;
  public:
  void clear_incremental();
  const std::string& incremental() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_incremental(ArgT0&& arg0, ArgT... args);
  std::string* mutable_incremental();
  PROTOBUF_NODISCARD std::string* release_incremental();
  void set_allocated_incremental(std::string* incremental);
  private:
  const std::string& _internal_incremental() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_incremental(const std::string& value);
  std::string* _internal_mutable_incremental();
  public:

  // optional bytes fingerprint = 5;
  bool has_fingerprint() const;
  private:
  bool _internal_has_fingerprint() const;
  public:
  void clear_fingerprint();
  const std::string& fingerprint() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fingerprint(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fingerprint();
  PROTOBUF_NODISCARD std::string* release_fingerprint();
  void set_allocated_fingerprint(std::string* fingerprint);
  private:
  const std::string& _internal_fingerprint() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fingerprint(const std::string& value);
  std::string* _internal_mutable_fingerprint();
  public:

  // optional bytes bootId = 6;
  bool has_bootid() const;
  private:
  bool _internal_has_bootid() const;
  public:
  void clear_bootid();
  const std::string& bootid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bootid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bootid();
  PROTOBUF_NODISCARD std::string* release_bootid();
  void set_allocated_bootid(std::string* bootid);
  private:
  const std::string& _internal_bootid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bootid(const std::string& value);
  std::string* _internal_mutable_bootid();
  public:

  // optional bytes androidId = 7;
  bool has_androidid() const;
  private:
  bool _internal_has_androidid() const;
  public:
  void clear_androidid();
  const std::string& androidid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_androidid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_androidid();
  PROTOBUF_NODISCARD std::string* release_androidid();
  void set_allocated_androidid(std::string* androidid);
  private:
  const std::string& _internal_androidid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_androidid(const std::string& value);
  std::string* _internal_mutable_androidid();
  public:

  // optional bytes baseBand = 8;
  bool has_baseband() const;
  private:
  bool _internal_has_baseband() const;
  public:
  void clear_baseband();
  const std::string& baseband() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_baseband(ArgT0&& arg0, ArgT... args);
  std::string* mutable_baseband();
  PROTOBUF_NODISCARD std::string* release_baseband();
  void set_allocated_baseband(std::string* baseband);
  private:
  const std::string& _internal_baseband() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_baseband(const std::string& value);
  std::string* _internal_mutable_baseband();
  public:

  // optional bytes innerVersion = 9;
  bool has_innerversion() const;
  private:
  bool _internal_has_innerversion() const;
  public:
  void clear_innerversion();
  const std::string& innerversion() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_innerversion(ArgT0&& arg0, ArgT... args);
  std::string* mutable_innerversion();
  PROTOBUF_NODISCARD std::string* release_innerversion();
  void set_allocated_innerversion(std::string* innerversion);
  private:
  const std::string& _internal_innerversion() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_innerversion(const std::string& value);
  std::string* _internal_mutable_innerversion();
  public:

  // @@protoc_insertion_point(class_scope:Flee.DevInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bootloader_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr procversion_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr codename_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr incremental_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fingerprint_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bootid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr androidid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr baseband_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr innerversion_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DevInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DevInfo

// optional bytes bootloader = 1;
inline bool DevInfo::_internal_has_bootloader() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DevInfo::has_bootloader() const {
  return _internal_has_bootloader();
}
inline void DevInfo::clear_bootloader() {
  _impl_.bootloader_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DevInfo::bootloader() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.bootloader)
  return _internal_bootloader();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_bootloader(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.bootloader_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.bootloader)
}
inline std::string* DevInfo::mutable_bootloader() {
  std::string* _s = _internal_mutable_bootloader();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.bootloader)
  return _s;
}
inline const std::string& DevInfo::_internal_bootloader() const {
  return _impl_.bootloader_.Get();
}
inline void DevInfo::_internal_set_bootloader(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.bootloader_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_bootloader() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.bootloader_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_bootloader() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.bootloader)
  if (!_internal_has_bootloader()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.bootloader_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bootloader_.IsDefault()) {
    _impl_.bootloader_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_bootloader(std::string* bootloader) {
  if (bootloader != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.bootloader_.SetAllocated(bootloader, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bootloader_.IsDefault()) {
    _impl_.bootloader_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.bootloader)
}

// optional bytes procVersion = 2;
inline bool DevInfo::_internal_has_procversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DevInfo::has_procversion() const {
  return _internal_has_procversion();
}
inline void DevInfo::clear_procversion() {
  _impl_.procversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& DevInfo::procversion() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.procVersion)
  return _internal_procversion();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_procversion(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.procversion_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.procVersion)
}
inline std::string* DevInfo::mutable_procversion() {
  std::string* _s = _internal_mutable_procversion();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.procVersion)
  return _s;
}
inline const std::string& DevInfo::_internal_procversion() const {
  return _impl_.procversion_.Get();
}
inline void DevInfo::_internal_set_procversion(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.procversion_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_procversion() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.procversion_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_procversion() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.procVersion)
  if (!_internal_has_procversion()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.procversion_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.procversion_.IsDefault()) {
    _impl_.procversion_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_procversion(std::string* procversion) {
  if (procversion != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.procversion_.SetAllocated(procversion, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.procversion_.IsDefault()) {
    _impl_.procversion_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.procVersion)
}

// optional bytes codename = 3;
inline bool DevInfo::_internal_has_codename() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool DevInfo::has_codename() const {
  return _internal_has_codename();
}
inline void DevInfo::clear_codename() {
  _impl_.codename_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& DevInfo::codename() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.codename)
  return _internal_codename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_codename(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.codename_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.codename)
}
inline std::string* DevInfo::mutable_codename() {
  std::string* _s = _internal_mutable_codename();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.codename)
  return _s;
}
inline const std::string& DevInfo::_internal_codename() const {
  return _impl_.codename_.Get();
}
inline void DevInfo::_internal_set_codename(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.codename_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_codename() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.codename_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_codename() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.codename)
  if (!_internal_has_codename()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.codename_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.codename_.IsDefault()) {
    _impl_.codename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_codename(std::string* codename) {
  if (codename != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.codename_.SetAllocated(codename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.codename_.IsDefault()) {
    _impl_.codename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.codename)
}

// optional bytes incremental = 4;
inline bool DevInfo::_internal_has_incremental() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool DevInfo::has_incremental() const {
  return _internal_has_incremental();
}
inline void DevInfo::clear_incremental() {
  _impl_.incremental_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& DevInfo::incremental() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.incremental)
  return _internal_incremental();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_incremental(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000008u;
 _impl_.incremental_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.incremental)
}
inline std::string* DevInfo::mutable_incremental() {
  std::string* _s = _internal_mutable_incremental();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.incremental)
  return _s;
}
inline const std::string& DevInfo::_internal_incremental() const {
  return _impl_.incremental_.Get();
}
inline void DevInfo::_internal_set_incremental(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.incremental_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_incremental() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.incremental_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_incremental() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.incremental)
  if (!_internal_has_incremental()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* p = _impl_.incremental_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.incremental_.IsDefault()) {
    _impl_.incremental_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_incremental(std::string* incremental) {
  if (incremental != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.incremental_.SetAllocated(incremental, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.incremental_.IsDefault()) {
    _impl_.incremental_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.incremental)
}

// optional bytes fingerprint = 5;
inline bool DevInfo::_internal_has_fingerprint() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool DevInfo::has_fingerprint() const {
  return _internal_has_fingerprint();
}
inline void DevInfo::clear_fingerprint() {
  _impl_.fingerprint_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& DevInfo::fingerprint() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.fingerprint)
  return _internal_fingerprint();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_fingerprint(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000010u;
 _impl_.fingerprint_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.fingerprint)
}
inline std::string* DevInfo::mutable_fingerprint() {
  std::string* _s = _internal_mutable_fingerprint();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.fingerprint)
  return _s;
}
inline const std::string& DevInfo::_internal_fingerprint() const {
  return _impl_.fingerprint_.Get();
}
inline void DevInfo::_internal_set_fingerprint(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.fingerprint_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_fingerprint() {
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.fingerprint_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_fingerprint() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.fingerprint)
  if (!_internal_has_fingerprint()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* p = _impl_.fingerprint_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fingerprint_.IsDefault()) {
    _impl_.fingerprint_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_fingerprint(std::string* fingerprint) {
  if (fingerprint != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.fingerprint_.SetAllocated(fingerprint, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fingerprint_.IsDefault()) {
    _impl_.fingerprint_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.fingerprint)
}

// optional bytes bootId = 6;
inline bool DevInfo::_internal_has_bootid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool DevInfo::has_bootid() const {
  return _internal_has_bootid();
}
inline void DevInfo::clear_bootid() {
  _impl_.bootid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& DevInfo::bootid() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.bootId)
  return _internal_bootid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_bootid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000020u;
 _impl_.bootid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.bootId)
}
inline std::string* DevInfo::mutable_bootid() {
  std::string* _s = _internal_mutable_bootid();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.bootId)
  return _s;
}
inline const std::string& DevInfo::_internal_bootid() const {
  return _impl_.bootid_.Get();
}
inline void DevInfo::_internal_set_bootid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.bootid_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_bootid() {
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.bootid_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_bootid() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.bootId)
  if (!_internal_has_bootid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* p = _impl_.bootid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bootid_.IsDefault()) {
    _impl_.bootid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_bootid(std::string* bootid) {
  if (bootid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.bootid_.SetAllocated(bootid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bootid_.IsDefault()) {
    _impl_.bootid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.bootId)
}

// optional bytes androidId = 7;
inline bool DevInfo::_internal_has_androidid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool DevInfo::has_androidid() const {
  return _internal_has_androidid();
}
inline void DevInfo::clear_androidid() {
  _impl_.androidid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const std::string& DevInfo::androidid() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.androidId)
  return _internal_androidid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_androidid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000040u;
 _impl_.androidid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.androidId)
}
inline std::string* DevInfo::mutable_androidid() {
  std::string* _s = _internal_mutable_androidid();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.androidId)
  return _s;
}
inline const std::string& DevInfo::_internal_androidid() const {
  return _impl_.androidid_.Get();
}
inline void DevInfo::_internal_set_androidid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.androidid_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_androidid() {
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.androidid_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_androidid() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.androidId)
  if (!_internal_has_androidid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* p = _impl_.androidid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.androidid_.IsDefault()) {
    _impl_.androidid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_androidid(std::string* androidid) {
  if (androidid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.androidid_.SetAllocated(androidid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.androidid_.IsDefault()) {
    _impl_.androidid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.androidId)
}

// optional bytes baseBand = 8;
inline bool DevInfo::_internal_has_baseband() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool DevInfo::has_baseband() const {
  return _internal_has_baseband();
}
inline void DevInfo::clear_baseband() {
  _impl_.baseband_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const std::string& DevInfo::baseband() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.baseBand)
  return _internal_baseband();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_baseband(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000080u;
 _impl_.baseband_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.baseBand)
}
inline std::string* DevInfo::mutable_baseband() {
  std::string* _s = _internal_mutable_baseband();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.baseBand)
  return _s;
}
inline const std::string& DevInfo::_internal_baseband() const {
  return _impl_.baseband_.Get();
}
inline void DevInfo::_internal_set_baseband(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.baseband_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_baseband() {
  _impl_._has_bits_[0] |= 0x00000080u;
  return _impl_.baseband_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_baseband() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.baseBand)
  if (!_internal_has_baseband()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080u;
  auto* p = _impl_.baseband_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.baseband_.IsDefault()) {
    _impl_.baseband_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_baseband(std::string* baseband) {
  if (baseband != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.baseband_.SetAllocated(baseband, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.baseband_.IsDefault()) {
    _impl_.baseband_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.baseBand)
}

// optional bytes innerVersion = 9;
inline bool DevInfo::_internal_has_innerversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool DevInfo::has_innerversion() const {
  return _internal_has_innerversion();
}
inline void DevInfo::clear_innerversion() {
  _impl_.innerversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const std::string& DevInfo::innerversion() const {
  // @@protoc_insertion_point(field_get:Flee.DevInfo.innerVersion)
  return _internal_innerversion();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DevInfo::set_innerversion(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000100u;
 _impl_.innerversion_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Flee.DevInfo.innerVersion)
}
inline std::string* DevInfo::mutable_innerversion() {
  std::string* _s = _internal_mutable_innerversion();
  // @@protoc_insertion_point(field_mutable:Flee.DevInfo.innerVersion)
  return _s;
}
inline const std::string& DevInfo::_internal_innerversion() const {
  return _impl_.innerversion_.Get();
}
inline void DevInfo::_internal_set_innerversion(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.innerversion_.Set(value, GetArenaForAllocation());
}
inline std::string* DevInfo::_internal_mutable_innerversion() {
  _impl_._has_bits_[0] |= 0x00000100u;
  return _impl_.innerversion_.Mutable(GetArenaForAllocation());
}
inline std::string* DevInfo::release_innerversion() {
  // @@protoc_insertion_point(field_release:Flee.DevInfo.innerVersion)
  if (!_internal_has_innerversion()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000100u;
  auto* p = _impl_.innerversion_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.innerversion_.IsDefault()) {
    _impl_.innerversion_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DevInfo::set_allocated_innerversion(std::string* innerversion) {
  if (innerversion != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.innerversion_.SetAllocated(innerversion, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.innerversion_.IsDefault()) {
    _impl_.innerversion_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Flee.DevInfo.innerVersion)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Flee

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DevInfo_2eproto
