// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DevInfo.proto

#include "DevInfo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Flee {
PROTOBUF_CONSTEXPR DevInfo::DevInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.bootloader_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.procversion_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.codename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.incremental_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fingerprint_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bootid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.androidid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.baseband_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.innerversion_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct DevInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DevInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DevInfoDefaultTypeInternal() {}
  union {
    DevInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DevInfoDefaultTypeInternal _DevInfo_default_instance_;
}  // namespace Flee
static ::_pb::Metadata file_level_metadata_DevInfo_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_DevInfo_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_DevInfo_2eproto = nullptr;

const uint32_t TableStruct_DevInfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.bootloader_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.procversion_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.codename_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.incremental_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.fingerprint_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.bootid_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.androidid_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.baseband_),
  PROTOBUF_FIELD_OFFSET(::Flee::DevInfo, _impl_.innerversion_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 15, -1, sizeof(::Flee::DevInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Flee::_DevInfo_default_instance_._instance,
};

const char descriptor_table_protodef_DevInfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rDevInfo.proto\022\004Flee\"\351\002\n\007DevInfo\022\027\n\nboo"
  "tloader\030\001 \001(\014H\000\210\001\001\022\030\n\013procVersion\030\002 \001(\014H"
  "\001\210\001\001\022\025\n\010codename\030\003 \001(\014H\002\210\001\001\022\030\n\013increment"
  "al\030\004 \001(\014H\003\210\001\001\022\030\n\013fingerprint\030\005 \001(\014H\004\210\001\001\022"
  "\023\n\006bootId\030\006 \001(\014H\005\210\001\001\022\026\n\tandroidId\030\007 \001(\014H"
  "\006\210\001\001\022\025\n\010baseBand\030\010 \001(\014H\007\210\001\001\022\031\n\014innerVers"
  "ion\030\t \001(\014H\010\210\001\001B\r\n\013_bootloaderB\016\n\014_procVe"
  "rsionB\013\n\t_codenameB\016\n\014_incrementalB\016\n\014_f"
  "ingerprintB\t\n\007_bootIdB\014\n\n_androidIdB\013\n\t_"
  "baseBandB\017\n\r_innerVersionb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_DevInfo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_DevInfo_2eproto = {
    false, false, 393, descriptor_table_protodef_DevInfo_2eproto,
    "DevInfo.proto",
    &descriptor_table_DevInfo_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_DevInfo_2eproto::offsets,
    file_level_metadata_DevInfo_2eproto, file_level_enum_descriptors_DevInfo_2eproto,
    file_level_service_descriptors_DevInfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_DevInfo_2eproto_getter() {
  return &descriptor_table_DevInfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_DevInfo_2eproto(&descriptor_table_DevInfo_2eproto);
namespace Flee {

// ===================================================================

class DevInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<DevInfo>()._impl_._has_bits_);
  static void set_has_bootloader(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_procversion(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_codename(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_incremental(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_fingerprint(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_bootid(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_androidid(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_baseband(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_innerversion(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
};

DevInfo::DevInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Flee.DevInfo)
}
DevInfo::DevInfo(const DevInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DevInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.bootloader_){}
    , decltype(_impl_.procversion_){}
    , decltype(_impl_.codename_){}
    , decltype(_impl_.incremental_){}
    , decltype(_impl_.fingerprint_){}
    , decltype(_impl_.bootid_){}
    , decltype(_impl_.androidid_){}
    , decltype(_impl_.baseband_){}
    , decltype(_impl_.innerversion_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.bootloader_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bootloader_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_bootloader()) {
    _this->_impl_.bootloader_.Set(from._internal_bootloader(), 
      _this->GetArenaForAllocation());
  }
  _impl_.procversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.procversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_procversion()) {
    _this->_impl_.procversion_.Set(from._internal_procversion(), 
      _this->GetArenaForAllocation());
  }
  _impl_.codename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.codename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_codename()) {
    _this->_impl_.codename_.Set(from._internal_codename(), 
      _this->GetArenaForAllocation());
  }
  _impl_.incremental_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.incremental_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_incremental()) {
    _this->_impl_.incremental_.Set(from._internal_incremental(), 
      _this->GetArenaForAllocation());
  }
  _impl_.fingerprint_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fingerprint_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_fingerprint()) {
    _this->_impl_.fingerprint_.Set(from._internal_fingerprint(), 
      _this->GetArenaForAllocation());
  }
  _impl_.bootid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bootid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_bootid()) {
    _this->_impl_.bootid_.Set(from._internal_bootid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.androidid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.androidid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_androidid()) {
    _this->_impl_.androidid_.Set(from._internal_androidid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.baseband_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.baseband_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_baseband()) {
    _this->_impl_.baseband_.Set(from._internal_baseband(), 
      _this->GetArenaForAllocation());
  }
  _impl_.innerversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.innerversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_innerversion()) {
    _this->_impl_.innerversion_.Set(from._internal_innerversion(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Flee.DevInfo)
}

inline void DevInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.bootloader_){}
    , decltype(_impl_.procversion_){}
    , decltype(_impl_.codename_){}
    , decltype(_impl_.incremental_){}
    , decltype(_impl_.fingerprint_){}
    , decltype(_impl_.bootid_){}
    , decltype(_impl_.androidid_){}
    , decltype(_impl_.baseband_){}
    , decltype(_impl_.innerversion_){}
  };
  _impl_.bootloader_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bootloader_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.procversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.procversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.codename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.codename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.incremental_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.incremental_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.fingerprint_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fingerprint_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.bootid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bootid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.androidid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.androidid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.baseband_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.baseband_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.innerversion_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.innerversion_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DevInfo::~DevInfo() {
  // @@protoc_insertion_point(destructor:Flee.DevInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DevInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bootloader_.Destroy();
  _impl_.procversion_.Destroy();
  _impl_.codename_.Destroy();
  _impl_.incremental_.Destroy();
  _impl_.fingerprint_.Destroy();
  _impl_.bootid_.Destroy();
  _impl_.androidid_.Destroy();
  _impl_.baseband_.Destroy();
  _impl_.innerversion_.Destroy();
}

void DevInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DevInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Flee.DevInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.bootloader_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.procversion_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.codename_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.incremental_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.fingerprint_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.bootid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      _impl_.androidid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      _impl_.baseband_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _impl_.innerversion_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DevInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional bytes bootloader = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_bootloader();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes procVersion = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_procversion();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes codename = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_codename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes incremental = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_incremental();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes fingerprint = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_fingerprint();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes bootId = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_bootid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes androidId = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_androidid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes baseBand = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_baseband();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes innerVersion = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_innerversion();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DevInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Flee.DevInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional bytes bootloader = 1;
  if (_internal_has_bootloader()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_bootloader(), target);
  }

  // optional bytes procVersion = 2;
  if (_internal_has_procversion()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_procversion(), target);
  }

  // optional bytes codename = 3;
  if (_internal_has_codename()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_codename(), target);
  }

  // optional bytes incremental = 4;
  if (_internal_has_incremental()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_incremental(), target);
  }

  // optional bytes fingerprint = 5;
  if (_internal_has_fingerprint()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_fingerprint(), target);
  }

  // optional bytes bootId = 6;
  if (_internal_has_bootid()) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_bootid(), target);
  }

  // optional bytes androidId = 7;
  if (_internal_has_androidid()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_androidid(), target);
  }

  // optional bytes baseBand = 8;
  if (_internal_has_baseband()) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_baseband(), target);
  }

  // optional bytes innerVersion = 9;
  if (_internal_has_innerversion()) {
    target = stream->WriteBytesMaybeAliased(
        9, this->_internal_innerversion(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Flee.DevInfo)
  return target;
}

size_t DevInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Flee.DevInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes bootloader = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_bootloader());
    }

    // optional bytes procVersion = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_procversion());
    }

    // optional bytes codename = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_codename());
    }

    // optional bytes incremental = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_incremental());
    }

    // optional bytes fingerprint = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_fingerprint());
    }

    // optional bytes bootId = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_bootid());
    }

    // optional bytes androidId = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_androidid());
    }

    // optional bytes baseBand = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_baseband());
    }

  }
  // optional bytes innerVersion = 9;
  if (cached_has_bits & 0x00000100u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_innerversion());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DevInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DevInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DevInfo::GetClassData() const { return &_class_data_; }


void DevInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DevInfo*>(&to_msg);
  auto& from = static_cast<const DevInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Flee.DevInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_bootloader(from._internal_bootloader());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_procversion(from._internal_procversion());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_codename(from._internal_codename());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_incremental(from._internal_incremental());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_fingerprint(from._internal_fingerprint());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_bootid(from._internal_bootid());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_set_androidid(from._internal_androidid());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_set_baseband(from._internal_baseband());
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_internal_set_innerversion(from._internal_innerversion());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DevInfo::CopyFrom(const DevInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Flee.DevInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DevInfo::IsInitialized() const {
  return true;
}

void DevInfo::InternalSwap(DevInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bootloader_, lhs_arena,
      &other->_impl_.bootloader_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.procversion_, lhs_arena,
      &other->_impl_.procversion_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.codename_, lhs_arena,
      &other->_impl_.codename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.incremental_, lhs_arena,
      &other->_impl_.incremental_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fingerprint_, lhs_arena,
      &other->_impl_.fingerprint_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bootid_, lhs_arena,
      &other->_impl_.bootid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.androidid_, lhs_arena,
      &other->_impl_.androidid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.baseband_, lhs_arena,
      &other->_impl_.baseband_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.innerversion_, lhs_arena,
      &other->_impl_.innerversion_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata DevInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DevInfo_2eproto_getter, &descriptor_table_DevInfo_2eproto_once,
      file_level_metadata_DevInfo_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Flee
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Flee::DevInfo*
Arena::CreateMaybeMessage< ::Flee::DevInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Flee::DevInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
