// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oidb0x769.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Oidb0x769_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Oidb0x769_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Oidb0x769_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Oidb0x769_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Oidb0x769_2eproto;
class ConfigSeq;
struct ConfigSeqDefaultTypeInternal;
extern ConfigSeqDefaultTypeInternal _ConfigSeq_default_instance_;
class QueryUinPackageUsageReq;
struct QueryUinPackageUsageReqDefaultTypeInternal;
extern QueryUinPackageUsageReqDefaultTypeInternal _QueryUinPackageUsageReq_default_instance_;
class ReqBody;
struct ReqBodyDefaultTypeInternal;
extern ReqBodyDefaultTypeInternal _ReqBody_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ConfigSeq* Arena::CreateMaybeMessage<::ConfigSeq>(Arena*);
template<> ::QueryUinPackageUsageReq* Arena::CreateMaybeMessage<::QueryUinPackageUsageReq>(Arena*);
template<> ::ReqBody* Arena::CreateMaybeMessage<::ReqBody>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ConfigSeq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ConfigSeq) */ {
 public:
  inline ConfigSeq() : ConfigSeq(nullptr) {}
  ~ConfigSeq() override;
  explicit PROTOBUF_CONSTEXPR ConfigSeq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConfigSeq(const ConfigSeq& from);
  ConfigSeq(ConfigSeq&& from) noexcept
    : ConfigSeq() {
    *this = ::std::move(from);
  }

  inline ConfigSeq& operator=(const ConfigSeq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConfigSeq& operator=(ConfigSeq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConfigSeq& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConfigSeq* internal_default_instance() {
    return reinterpret_cast<const ConfigSeq*>(
               &_ConfigSeq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ConfigSeq& a, ConfigSeq& b) {
    a.Swap(&b);
  }
  inline void Swap(ConfigSeq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConfigSeq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConfigSeq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConfigSeq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ConfigSeq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ConfigSeq& from) {
    ConfigSeq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConfigSeq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ConfigSeq";
  }
  protected:
  explicit ConfigSeq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kVersionFieldNumber = 2,
  };
  // optional int32 type = 1;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // optional int32 version = 2;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  int32_t version() const;
  void set_version(int32_t value);
  private:
  int32_t _internal_version() const;
  void _internal_set_version(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ConfigSeq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int32_t type_;
    int32_t version_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Oidb0x769_2eproto;
};
// -------------------------------------------------------------------

class QueryUinPackageUsageReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QueryUinPackageUsageReq) */ {
 public:
  inline QueryUinPackageUsageReq() : QueryUinPackageUsageReq(nullptr) {}
  ~QueryUinPackageUsageReq() override;
  explicit PROTOBUF_CONSTEXPR QueryUinPackageUsageReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QueryUinPackageUsageReq(const QueryUinPackageUsageReq& from);
  QueryUinPackageUsageReq(QueryUinPackageUsageReq&& from) noexcept
    : QueryUinPackageUsageReq() {
    *this = ::std::move(from);
  }

  inline QueryUinPackageUsageReq& operator=(const QueryUinPackageUsageReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryUinPackageUsageReq& operator=(QueryUinPackageUsageReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryUinPackageUsageReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryUinPackageUsageReq* internal_default_instance() {
    return reinterpret_cast<const QueryUinPackageUsageReq*>(
               &_QueryUinPackageUsageReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(QueryUinPackageUsageReq& a, QueryUinPackageUsageReq& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryUinPackageUsageReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryUinPackageUsageReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryUinPackageUsageReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QueryUinPackageUsageReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QueryUinPackageUsageReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QueryUinPackageUsageReq& from) {
    QueryUinPackageUsageReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryUinPackageUsageReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QueryUinPackageUsageReq";
  }
  protected:
  explicit QueryUinPackageUsageReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUinFileSizeFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // optional int64 uinFileSize = 2;
  bool has_uinfilesize() const;
  private:
  bool _internal_has_uinfilesize() const;
  public:
  void clear_uinfilesize();
  int64_t uinfilesize() const;
  void set_uinfilesize(int64_t value);
  private:
  int64_t _internal_uinfilesize() const;
  void _internal_set_uinfilesize(int64_t value);
  public:

  // optional int32 type = 1;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:QueryUinPackageUsageReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int64_t uinfilesize_;
    int32_t type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Oidb0x769_2eproto;
};
// -------------------------------------------------------------------

class ReqBody final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ReqBody) */ {
 public:
  inline ReqBody() : ReqBody(nullptr) {}
  ~ReqBody() override;
  explicit PROTOBUF_CONSTEXPR ReqBody(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReqBody(const ReqBody& from);
  ReqBody(ReqBody&& from) noexcept
    : ReqBody() {
    *this = ::std::move(from);
  }

  inline ReqBody& operator=(const ReqBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqBody& operator=(ReqBody&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqBody* internal_default_instance() {
    return reinterpret_cast<const ReqBody*>(
               &_ReqBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReqBody& a, ReqBody& b) {
    a.Swap(&b);
  }
  inline void Swap(ReqBody* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqBody* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqBody* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReqBody>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReqBody& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReqBody& from) {
    ReqBody::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqBody* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ReqBody";
  }
  protected:
  explicit ReqBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConfigListFieldNumber = 1,
    kInfoFieldNumber = 3,
    kProvinceFieldNumber = 4,
    kCityFieldNumber = 5,
    kQueryUinPackageUsageReqFieldNumber = 101,
    kReqDebugMsgFieldNumber = 6,
  };
  // repeated .ConfigSeq configList = 1;
  int configlist_size() const;
  private:
  int _internal_configlist_size() const;
  public:
  void clear_configlist();
  ::ConfigSeq* mutable_configlist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ConfigSeq >*
      mutable_configlist();
  private:
  const ::ConfigSeq& _internal_configlist(int index) const;
  ::ConfigSeq* _internal_add_configlist();
  public:
  const ::ConfigSeq& configlist(int index) const;
  ::ConfigSeq* add_configlist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ConfigSeq >&
      configlist() const;

  // optional string info = 3;
  bool has_info() const;
  private:
  bool _internal_has_info() const;
  public:
  void clear_info();
  const std::string& info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_info();
  PROTOBUF_NODISCARD std::string* release_info();
  void set_allocated_info(std::string* info);
  private:
  const std::string& _internal_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_info(const std::string& value);
  std::string* _internal_mutable_info();
  public:

  // optional string province = 4;
  bool has_province() const;
  private:
  bool _internal_has_province() const;
  public:
  void clear_province();
  const std::string& province() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_province(ArgT0&& arg0, ArgT... args);
  std::string* mutable_province();
  PROTOBUF_NODISCARD std::string* release_province();
  void set_allocated_province(std::string* province);
  private:
  const std::string& _internal_province() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_province(const std::string& value);
  std::string* _internal_mutable_province();
  public:

  // optional string city = 5;
  bool has_city() const;
  private:
  bool _internal_has_city() const;
  public:
  void clear_city();
  const std::string& city() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_city(ArgT0&& arg0, ArgT... args);
  std::string* mutable_city();
  PROTOBUF_NODISCARD std::string* release_city();
  void set_allocated_city(std::string* city);
  private:
  const std::string& _internal_city() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_city(const std::string& value);
  std::string* _internal_mutable_city();
  public:

  // optional .QueryUinPackageUsageReq queryUinPackageUsageReq = 101;
  bool has_queryuinpackageusagereq() const;
  private:
  bool _internal_has_queryuinpackageusagereq() const;
  public:
  void clear_queryuinpackageusagereq();
  const ::QueryUinPackageUsageReq& queryuinpackageusagereq() const;
  PROTOBUF_NODISCARD ::QueryUinPackageUsageReq* release_queryuinpackageusagereq();
  ::QueryUinPackageUsageReq* mutable_queryuinpackageusagereq();
  void set_allocated_queryuinpackageusagereq(::QueryUinPackageUsageReq* queryuinpackageusagereq);
  private:
  const ::QueryUinPackageUsageReq& _internal_queryuinpackageusagereq() const;
  ::QueryUinPackageUsageReq* _internal_mutable_queryuinpackageusagereq();
  public:
  void unsafe_arena_set_allocated_queryuinpackageusagereq(
      ::QueryUinPackageUsageReq* queryuinpackageusagereq);
  ::QueryUinPackageUsageReq* unsafe_arena_release_queryuinpackageusagereq();

  // optional int32 reqDebugMsg = 6;
  bool has_reqdebugmsg() const;
  private:
  bool _internal_has_reqdebugmsg() const;
  public:
  void clear_reqdebugmsg();
  int32_t reqdebugmsg() const;
  void set_reqdebugmsg(int32_t value);
  private:
  int32_t _internal_reqdebugmsg() const;
  void _internal_set_reqdebugmsg(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ReqBody)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ConfigSeq > configlist_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr info_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr province_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr city_;
    ::QueryUinPackageUsageReq* queryuinpackageusagereq_;
    int32_t reqdebugmsg_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Oidb0x769_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConfigSeq

// optional int32 type = 1;
inline bool ConfigSeq::_internal_has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ConfigSeq::has_type() const {
  return _internal_has_type();
}
inline void ConfigSeq::clear_type() {
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t ConfigSeq::_internal_type() const {
  return _impl_.type_;
}
inline int32_t ConfigSeq::type() const {
  // @@protoc_insertion_point(field_get:ConfigSeq.type)
  return _internal_type();
}
inline void ConfigSeq::_internal_set_type(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.type_ = value;
}
inline void ConfigSeq::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:ConfigSeq.type)
}

// optional int32 version = 2;
inline bool ConfigSeq::_internal_has_version() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ConfigSeq::has_version() const {
  return _internal_has_version();
}
inline void ConfigSeq::clear_version() {
  _impl_.version_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t ConfigSeq::_internal_version() const {
  return _impl_.version_;
}
inline int32_t ConfigSeq::version() const {
  // @@protoc_insertion_point(field_get:ConfigSeq.version)
  return _internal_version();
}
inline void ConfigSeq::_internal_set_version(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.version_ = value;
}
inline void ConfigSeq::set_version(int32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:ConfigSeq.version)
}

// -------------------------------------------------------------------

// QueryUinPackageUsageReq

// optional int32 type = 1;
inline bool QueryUinPackageUsageReq::_internal_has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool QueryUinPackageUsageReq::has_type() const {
  return _internal_has_type();
}
inline void QueryUinPackageUsageReq::clear_type() {
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t QueryUinPackageUsageReq::_internal_type() const {
  return _impl_.type_;
}
inline int32_t QueryUinPackageUsageReq::type() const {
  // @@protoc_insertion_point(field_get:QueryUinPackageUsageReq.type)
  return _internal_type();
}
inline void QueryUinPackageUsageReq::_internal_set_type(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.type_ = value;
}
inline void QueryUinPackageUsageReq::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:QueryUinPackageUsageReq.type)
}

// optional int64 uinFileSize = 2;
inline bool QueryUinPackageUsageReq::_internal_has_uinfilesize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool QueryUinPackageUsageReq::has_uinfilesize() const {
  return _internal_has_uinfilesize();
}
inline void QueryUinPackageUsageReq::clear_uinfilesize() {
  _impl_.uinfilesize_ = int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int64_t QueryUinPackageUsageReq::_internal_uinfilesize() const {
  return _impl_.uinfilesize_;
}
inline int64_t QueryUinPackageUsageReq::uinfilesize() const {
  // @@protoc_insertion_point(field_get:QueryUinPackageUsageReq.uinFileSize)
  return _internal_uinfilesize();
}
inline void QueryUinPackageUsageReq::_internal_set_uinfilesize(int64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.uinfilesize_ = value;
}
inline void QueryUinPackageUsageReq::set_uinfilesize(int64_t value) {
  _internal_set_uinfilesize(value);
  // @@protoc_insertion_point(field_set:QueryUinPackageUsageReq.uinFileSize)
}

// -------------------------------------------------------------------

// ReqBody

// repeated .ConfigSeq configList = 1;
inline int ReqBody::_internal_configlist_size() const {
  return _impl_.configlist_.size();
}
inline int ReqBody::configlist_size() const {
  return _internal_configlist_size();
}
inline void ReqBody::clear_configlist() {
  _impl_.configlist_.Clear();
}
inline ::ConfigSeq* ReqBody::mutable_configlist(int index) {
  // @@protoc_insertion_point(field_mutable:ReqBody.configList)
  return _impl_.configlist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ConfigSeq >*
ReqBody::mutable_configlist() {
  // @@protoc_insertion_point(field_mutable_list:ReqBody.configList)
  return &_impl_.configlist_;
}
inline const ::ConfigSeq& ReqBody::_internal_configlist(int index) const {
  return _impl_.configlist_.Get(index);
}
inline const ::ConfigSeq& ReqBody::configlist(int index) const {
  // @@protoc_insertion_point(field_get:ReqBody.configList)
  return _internal_configlist(index);
}
inline ::ConfigSeq* ReqBody::_internal_add_configlist() {
  return _impl_.configlist_.Add();
}
inline ::ConfigSeq* ReqBody::add_configlist() {
  ::ConfigSeq* _add = _internal_add_configlist();
  // @@protoc_insertion_point(field_add:ReqBody.configList)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ConfigSeq >&
ReqBody::configlist() const {
  // @@protoc_insertion_point(field_list:ReqBody.configList)
  return _impl_.configlist_;
}

// optional string info = 3;
inline bool ReqBody::_internal_has_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ReqBody::has_info() const {
  return _internal_has_info();
}
inline void ReqBody::clear_info() {
  _impl_.info_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ReqBody::info() const {
  // @@protoc_insertion_point(field_get:ReqBody.info)
  return _internal_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReqBody::set_info(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.info_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ReqBody.info)
}
inline std::string* ReqBody::mutable_info() {
  std::string* _s = _internal_mutable_info();
  // @@protoc_insertion_point(field_mutable:ReqBody.info)
  return _s;
}
inline const std::string& ReqBody::_internal_info() const {
  return _impl_.info_.Get();
}
inline void ReqBody::_internal_set_info(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.info_.Set(value, GetArenaForAllocation());
}
inline std::string* ReqBody::_internal_mutable_info() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.info_.Mutable(GetArenaForAllocation());
}
inline std::string* ReqBody::release_info() {
  // @@protoc_insertion_point(field_release:ReqBody.info)
  if (!_internal_has_info()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.info_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.info_.IsDefault()) {
    _impl_.info_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReqBody::set_allocated_info(std::string* info) {
  if (info != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.info_.SetAllocated(info, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.info_.IsDefault()) {
    _impl_.info_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ReqBody.info)
}

// optional string province = 4;
inline bool ReqBody::_internal_has_province() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ReqBody::has_province() const {
  return _internal_has_province();
}
inline void ReqBody::clear_province() {
  _impl_.province_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ReqBody::province() const {
  // @@protoc_insertion_point(field_get:ReqBody.province)
  return _internal_province();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReqBody::set_province(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.province_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ReqBody.province)
}
inline std::string* ReqBody::mutable_province() {
  std::string* _s = _internal_mutable_province();
  // @@protoc_insertion_point(field_mutable:ReqBody.province)
  return _s;
}
inline const std::string& ReqBody::_internal_province() const {
  return _impl_.province_.Get();
}
inline void ReqBody::_internal_set_province(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.province_.Set(value, GetArenaForAllocation());
}
inline std::string* ReqBody::_internal_mutable_province() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.province_.Mutable(GetArenaForAllocation());
}
inline std::string* ReqBody::release_province() {
  // @@protoc_insertion_point(field_release:ReqBody.province)
  if (!_internal_has_province()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.province_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.province_.IsDefault()) {
    _impl_.province_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReqBody::set_allocated_province(std::string* province) {
  if (province != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.province_.SetAllocated(province, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.province_.IsDefault()) {
    _impl_.province_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ReqBody.province)
}

// optional string city = 5;
inline bool ReqBody::_internal_has_city() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ReqBody::has_city() const {
  return _internal_has_city();
}
inline void ReqBody::clear_city() {
  _impl_.city_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ReqBody::city() const {
  // @@protoc_insertion_point(field_get:ReqBody.city)
  return _internal_city();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReqBody::set_city(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.city_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ReqBody.city)
}
inline std::string* ReqBody::mutable_city() {
  std::string* _s = _internal_mutable_city();
  // @@protoc_insertion_point(field_mutable:ReqBody.city)
  return _s;
}
inline const std::string& ReqBody::_internal_city() const {
  return _impl_.city_.Get();
}
inline void ReqBody::_internal_set_city(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.city_.Set(value, GetArenaForAllocation());
}
inline std::string* ReqBody::_internal_mutable_city() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.city_.Mutable(GetArenaForAllocation());
}
inline std::string* ReqBody::release_city() {
  // @@protoc_insertion_point(field_release:ReqBody.city)
  if (!_internal_has_city()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.city_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.city_.IsDefault()) {
    _impl_.city_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void ReqBody::set_allocated_city(std::string* city) {
  if (city != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.city_.SetAllocated(city, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.city_.IsDefault()) {
    _impl_.city_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ReqBody.city)
}

// optional int32 reqDebugMsg = 6;
inline bool ReqBody::_internal_has_reqdebugmsg() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool ReqBody::has_reqdebugmsg() const {
  return _internal_has_reqdebugmsg();
}
inline void ReqBody::clear_reqdebugmsg() {
  _impl_.reqdebugmsg_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline int32_t ReqBody::_internal_reqdebugmsg() const {
  return _impl_.reqdebugmsg_;
}
inline int32_t ReqBody::reqdebugmsg() const {
  // @@protoc_insertion_point(field_get:ReqBody.reqDebugMsg)
  return _internal_reqdebugmsg();
}
inline void ReqBody::_internal_set_reqdebugmsg(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.reqdebugmsg_ = value;
}
inline void ReqBody::set_reqdebugmsg(int32_t value) {
  _internal_set_reqdebugmsg(value);
  // @@protoc_insertion_point(field_set:ReqBody.reqDebugMsg)
}

// optional .QueryUinPackageUsageReq queryUinPackageUsageReq = 101;
inline bool ReqBody::_internal_has_queryuinpackageusagereq() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.queryuinpackageusagereq_ != nullptr);
  return value;
}
inline bool ReqBody::has_queryuinpackageusagereq() const {
  return _internal_has_queryuinpackageusagereq();
}
inline void ReqBody::clear_queryuinpackageusagereq() {
  if (_impl_.queryuinpackageusagereq_ != nullptr) _impl_.queryuinpackageusagereq_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::QueryUinPackageUsageReq& ReqBody::_internal_queryuinpackageusagereq() const {
  const ::QueryUinPackageUsageReq* p = _impl_.queryuinpackageusagereq_;
  return p != nullptr ? *p : reinterpret_cast<const ::QueryUinPackageUsageReq&>(
      ::_QueryUinPackageUsageReq_default_instance_);
}
inline const ::QueryUinPackageUsageReq& ReqBody::queryuinpackageusagereq() const {
  // @@protoc_insertion_point(field_get:ReqBody.queryUinPackageUsageReq)
  return _internal_queryuinpackageusagereq();
}
inline void ReqBody::unsafe_arena_set_allocated_queryuinpackageusagereq(
    ::QueryUinPackageUsageReq* queryuinpackageusagereq) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.queryuinpackageusagereq_);
  }
  _impl_.queryuinpackageusagereq_ = queryuinpackageusagereq;
  if (queryuinpackageusagereq) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ReqBody.queryUinPackageUsageReq)
}
inline ::QueryUinPackageUsageReq* ReqBody::release_queryuinpackageusagereq() {
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::QueryUinPackageUsageReq* temp = _impl_.queryuinpackageusagereq_;
  _impl_.queryuinpackageusagereq_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::QueryUinPackageUsageReq* ReqBody::unsafe_arena_release_queryuinpackageusagereq() {
  // @@protoc_insertion_point(field_release:ReqBody.queryUinPackageUsageReq)
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::QueryUinPackageUsageReq* temp = _impl_.queryuinpackageusagereq_;
  _impl_.queryuinpackageusagereq_ = nullptr;
  return temp;
}
inline ::QueryUinPackageUsageReq* ReqBody::_internal_mutable_queryuinpackageusagereq() {
  _impl_._has_bits_[0] |= 0x00000008u;
  if (_impl_.queryuinpackageusagereq_ == nullptr) {
    auto* p = CreateMaybeMessage<::QueryUinPackageUsageReq>(GetArenaForAllocation());
    _impl_.queryuinpackageusagereq_ = p;
  }
  return _impl_.queryuinpackageusagereq_;
}
inline ::QueryUinPackageUsageReq* ReqBody::mutable_queryuinpackageusagereq() {
  ::QueryUinPackageUsageReq* _msg = _internal_mutable_queryuinpackageusagereq();
  // @@protoc_insertion_point(field_mutable:ReqBody.queryUinPackageUsageReq)
  return _msg;
}
inline void ReqBody::set_allocated_queryuinpackageusagereq(::QueryUinPackageUsageReq* queryuinpackageusagereq) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.queryuinpackageusagereq_;
  }
  if (queryuinpackageusagereq) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(queryuinpackageusagereq);
    if (message_arena != submessage_arena) {
      queryuinpackageusagereq = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, queryuinpackageusagereq, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.queryuinpackageusagereq_ = queryuinpackageusagereq;
  // @@protoc_insertion_point(field_set_allocated:ReqBody.queryUinPackageUsageReq)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Oidb0x769_2eproto
