// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oidb0x769.proto

#include "Oidb0x769.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ConfigSeq::ConfigSeq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.version_)*/0} {}
struct ConfigSeqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigSeqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigSeqDefaultTypeInternal() {}
  union {
    ConfigSeq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigSeqDefaultTypeInternal _ConfigSeq_default_instance_;
PROTOBUF_CONSTEXPR QueryUinPackageUsageReq::QueryUinPackageUsageReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.uinfilesize_)*/int64_t{0}
  , /*decltype(_impl_.type_)*/0} {}
struct QueryUinPackageUsageReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QueryUinPackageUsageReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~QueryUinPackageUsageReqDefaultTypeInternal() {}
  union {
    QueryUinPackageUsageReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QueryUinPackageUsageReqDefaultTypeInternal _QueryUinPackageUsageReq_default_instance_;
PROTOBUF_CONSTEXPR ReqBody::ReqBody(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.configlist_)*/{}
  , /*decltype(_impl_.info_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.province_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.city_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.queryuinpackageusagereq_)*/nullptr
  , /*decltype(_impl_.reqdebugmsg_)*/0} {}
struct ReqBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqBodyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqBodyDefaultTypeInternal() {}
  union {
    ReqBody _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqBodyDefaultTypeInternal _ReqBody_default_instance_;
static ::_pb::Metadata file_level_metadata_Oidb0x769_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Oidb0x769_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Oidb0x769_2eproto = nullptr;

const uint32_t TableStruct_Oidb0x769_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::ConfigSeq, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::ConfigSeq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ConfigSeq, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::ConfigSeq, _impl_.version_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::QueryUinPackageUsageReq, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::QueryUinPackageUsageReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::QueryUinPackageUsageReq, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::QueryUinPackageUsageReq, _impl_.uinfilesize_),
  1,
  0,
  PROTOBUF_FIELD_OFFSET(::ReqBody, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::ReqBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ReqBody, _impl_.configlist_),
  PROTOBUF_FIELD_OFFSET(::ReqBody, _impl_.info_),
  PROTOBUF_FIELD_OFFSET(::ReqBody, _impl_.province_),
  PROTOBUF_FIELD_OFFSET(::ReqBody, _impl_.city_),
  PROTOBUF_FIELD_OFFSET(::ReqBody, _impl_.reqdebugmsg_),
  PROTOBUF_FIELD_OFFSET(::ReqBody, _impl_.queryuinpackageusagereq_),
  ~0u,
  0,
  1,
  2,
  4,
  3,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::ConfigSeq)},
  { 10, 18, -1, sizeof(::QueryUinPackageUsageReq)},
  { 20, 32, -1, sizeof(::ReqBody)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ConfigSeq_default_instance_._instance,
  &::_QueryUinPackageUsageReq_default_instance_._instance,
  &::_ReqBody_default_instance_._instance,
};

const char descriptor_table_protodef_Oidb0x769_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017Oidb0x769.proto\"*\n\tConfigSeq\022\014\n\004type\030\001"
  " \001(\005\022\017\n\007version\030\002 \001(\005\"<\n\027QueryUinPackage"
  "UsageReq\022\014\n\004type\030\001 \001(\005\022\023\n\013uinFileSize\030\002 "
  "\001(\003\"\247\001\n\007ReqBody\022\036\n\nconfigList\030\001 \003(\0132\n.Co"
  "nfigSeq\022\014\n\004info\030\003 \001(\t\022\020\n\010province\030\004 \001(\t\022"
  "\014\n\004city\030\005 \001(\t\022\023\n\013reqDebugMsg\030\006 \001(\005\0229\n\027qu"
  "eryUinPackageUsageReq\030e \001(\0132\030.QueryUinPa"
  "ckageUsageReq"
  ;
static ::_pbi::once_flag descriptor_table_Oidb0x769_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Oidb0x769_2eproto = {
    false, false, 293, descriptor_table_protodef_Oidb0x769_2eproto,
    "Oidb0x769.proto",
    &descriptor_table_Oidb0x769_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_Oidb0x769_2eproto::offsets,
    file_level_metadata_Oidb0x769_2eproto, file_level_enum_descriptors_Oidb0x769_2eproto,
    file_level_service_descriptors_Oidb0x769_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Oidb0x769_2eproto_getter() {
  return &descriptor_table_Oidb0x769_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Oidb0x769_2eproto(&descriptor_table_Oidb0x769_2eproto);

// ===================================================================

class ConfigSeq::_Internal {
 public:
  using HasBits = decltype(std::declval<ConfigSeq>()._impl_._has_bits_);
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_version(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

ConfigSeq::ConfigSeq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ConfigSeq)
}
ConfigSeq::ConfigSeq(const ConfigSeq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ConfigSeq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){}
    , decltype(_impl_.version_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.version_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.version_));
  // @@protoc_insertion_point(copy_constructor:ConfigSeq)
}

inline void ConfigSeq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.version_){0}
  };
}

ConfigSeq::~ConfigSeq() {
  // @@protoc_insertion_point(destructor:ConfigSeq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ConfigSeq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ConfigSeq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ConfigSeq::Clear() {
// @@protoc_insertion_point(message_clear_start:ConfigSeq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.version_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.version_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConfigSeq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_type(&has_bits);
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_version(&has_bits);
          _impl_.version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ConfigSeq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ConfigSeq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 type = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_type(), target);
  }

  // optional int32 version = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ConfigSeq)
  return target;
}

size_t ConfigSeq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ConfigSeq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int32 type = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_type());
    }

    // optional int32 version = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_version());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ConfigSeq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ConfigSeq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ConfigSeq::GetClassData() const { return &_class_data_; }


void ConfigSeq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ConfigSeq*>(&to_msg);
  auto& from = static_cast<const ConfigSeq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ConfigSeq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.version_ = from._impl_.version_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ConfigSeq::CopyFrom(const ConfigSeq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConfigSeq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConfigSeq::IsInitialized() const {
  return true;
}

void ConfigSeq::InternalSwap(ConfigSeq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ConfigSeq, _impl_.version_)
      + sizeof(ConfigSeq::_impl_.version_)
      - PROTOBUF_FIELD_OFFSET(ConfigSeq, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ConfigSeq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Oidb0x769_2eproto_getter, &descriptor_table_Oidb0x769_2eproto_once,
      file_level_metadata_Oidb0x769_2eproto[0]);
}

// ===================================================================

class QueryUinPackageUsageReq::_Internal {
 public:
  using HasBits = decltype(std::declval<QueryUinPackageUsageReq>()._impl_._has_bits_);
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_uinfilesize(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

QueryUinPackageUsageReq::QueryUinPackageUsageReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:QueryUinPackageUsageReq)
}
QueryUinPackageUsageReq::QueryUinPackageUsageReq(const QueryUinPackageUsageReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  QueryUinPackageUsageReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.uinfilesize_){}
    , decltype(_impl_.type_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.uinfilesize_, &from._impl_.uinfilesize_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.type_) -
    reinterpret_cast<char*>(&_impl_.uinfilesize_)) + sizeof(_impl_.type_));
  // @@protoc_insertion_point(copy_constructor:QueryUinPackageUsageReq)
}

inline void QueryUinPackageUsageReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.uinfilesize_){int64_t{0}}
    , decltype(_impl_.type_){0}
  };
}

QueryUinPackageUsageReq::~QueryUinPackageUsageReq() {
  // @@protoc_insertion_point(destructor:QueryUinPackageUsageReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void QueryUinPackageUsageReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void QueryUinPackageUsageReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void QueryUinPackageUsageReq::Clear() {
// @@protoc_insertion_point(message_clear_start:QueryUinPackageUsageReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.uinfilesize_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.type_) -
        reinterpret_cast<char*>(&_impl_.uinfilesize_)) + sizeof(_impl_.type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QueryUinPackageUsageReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_type(&has_bits);
          _impl_.type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int64 uinFileSize = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_uinfilesize(&has_bits);
          _impl_.uinfilesize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* QueryUinPackageUsageReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QueryUinPackageUsageReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 type = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_type(), target);
  }

  // optional int64 uinFileSize = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_uinfilesize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QueryUinPackageUsageReq)
  return target;
}

size_t QueryUinPackageUsageReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QueryUinPackageUsageReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int64 uinFileSize = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_uinfilesize());
    }

    // optional int32 type = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_type());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QueryUinPackageUsageReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    QueryUinPackageUsageReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QueryUinPackageUsageReq::GetClassData() const { return &_class_data_; }


void QueryUinPackageUsageReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<QueryUinPackageUsageReq*>(&to_msg);
  auto& from = static_cast<const QueryUinPackageUsageReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:QueryUinPackageUsageReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.uinfilesize_ = from._impl_.uinfilesize_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QueryUinPackageUsageReq::CopyFrom(const QueryUinPackageUsageReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QueryUinPackageUsageReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QueryUinPackageUsageReq::IsInitialized() const {
  return true;
}

void QueryUinPackageUsageReq::InternalSwap(QueryUinPackageUsageReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QueryUinPackageUsageReq, _impl_.type_)
      + sizeof(QueryUinPackageUsageReq::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(QueryUinPackageUsageReq, _impl_.uinfilesize_)>(
          reinterpret_cast<char*>(&_impl_.uinfilesize_),
          reinterpret_cast<char*>(&other->_impl_.uinfilesize_));
}

::PROTOBUF_NAMESPACE_ID::Metadata QueryUinPackageUsageReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Oidb0x769_2eproto_getter, &descriptor_table_Oidb0x769_2eproto_once,
      file_level_metadata_Oidb0x769_2eproto[1]);
}

// ===================================================================

class ReqBody::_Internal {
 public:
  using HasBits = decltype(std::declval<ReqBody>()._impl_._has_bits_);
  static void set_has_info(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_province(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_city(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_reqdebugmsg(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::QueryUinPackageUsageReq& queryuinpackageusagereq(const ReqBody* msg);
  static void set_has_queryuinpackageusagereq(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::QueryUinPackageUsageReq&
ReqBody::_Internal::queryuinpackageusagereq(const ReqBody* msg) {
  return *msg->_impl_.queryuinpackageusagereq_;
}
ReqBody::ReqBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ReqBody)
}
ReqBody::ReqBody(const ReqBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReqBody* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.configlist_){from._impl_.configlist_}
    , decltype(_impl_.info_){}
    , decltype(_impl_.province_){}
    , decltype(_impl_.city_){}
    , decltype(_impl_.queryuinpackageusagereq_){nullptr}
    , decltype(_impl_.reqdebugmsg_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.info_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.info_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_info()) {
    _this->_impl_.info_.Set(from._internal_info(), 
      _this->GetArenaForAllocation());
  }
  _impl_.province_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.province_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_province()) {
    _this->_impl_.province_.Set(from._internal_province(), 
      _this->GetArenaForAllocation());
  }
  _impl_.city_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.city_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_city()) {
    _this->_impl_.city_.Set(from._internal_city(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_queryuinpackageusagereq()) {
    _this->_impl_.queryuinpackageusagereq_ = new ::QueryUinPackageUsageReq(*from._impl_.queryuinpackageusagereq_);
  }
  _this->_impl_.reqdebugmsg_ = from._impl_.reqdebugmsg_;
  // @@protoc_insertion_point(copy_constructor:ReqBody)
}

inline void ReqBody::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.configlist_){arena}
    , decltype(_impl_.info_){}
    , decltype(_impl_.province_){}
    , decltype(_impl_.city_){}
    , decltype(_impl_.queryuinpackageusagereq_){nullptr}
    , decltype(_impl_.reqdebugmsg_){0}
  };
  _impl_.info_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.info_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.province_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.province_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.city_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.city_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReqBody::~ReqBody() {
  // @@protoc_insertion_point(destructor:ReqBody)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReqBody::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.configlist_.~RepeatedPtrField();
  _impl_.info_.Destroy();
  _impl_.province_.Destroy();
  _impl_.city_.Destroy();
  if (this != internal_default_instance()) delete _impl_.queryuinpackageusagereq_;
}

void ReqBody::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReqBody::Clear() {
// @@protoc_insertion_point(message_clear_start:ReqBody)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.configlist_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.info_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.province_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.city_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(_impl_.queryuinpackageusagereq_ != nullptr);
      _impl_.queryuinpackageusagereq_->Clear();
    }
  }
  _impl_.reqdebugmsg_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqBody::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .ConfigSeq configList = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_configlist(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional string info = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_info();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "ReqBody.info");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string province = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_province();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "ReqBody.province");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string city = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_city();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "ReqBody.city");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional int32 reqDebugMsg = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_reqdebugmsg(&has_bits);
          _impl_.reqdebugmsg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .QueryUinPackageUsageReq queryUinPackageUsageReq = 101;
      case 101:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_queryuinpackageusagereq(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReqBody::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ReqBody)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ConfigSeq configList = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_configlist_size()); i < n; i++) {
    const auto& repfield = this->_internal_configlist(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional string info = 3;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_info().data(), static_cast<int>(this->_internal_info().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "ReqBody.info");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_info(), target);
  }

  // optional string province = 4;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_province().data(), static_cast<int>(this->_internal_province().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "ReqBody.province");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_province(), target);
  }

  // optional string city = 5;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_city().data(), static_cast<int>(this->_internal_city().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "ReqBody.city");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_city(), target);
  }

  // optional int32 reqDebugMsg = 6;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_reqdebugmsg(), target);
  }

  // optional .QueryUinPackageUsageReq queryUinPackageUsageReq = 101;
  if (cached_has_bits & 0x00000008u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(101, _Internal::queryuinpackageusagereq(this),
        _Internal::queryuinpackageusagereq(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ReqBody)
  return target;
}

size_t ReqBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ReqBody)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ConfigSeq configList = 1;
  total_size += 1UL * this->_internal_configlist_size();
  for (const auto& msg : this->_impl_.configlist_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional string info = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_info());
    }

    // optional string province = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_province());
    }

    // optional string city = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_city());
    }

    // optional .QueryUinPackageUsageReq queryUinPackageUsageReq = 101;
    if (cached_has_bits & 0x00000008u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.queryuinpackageusagereq_);
    }

    // optional int32 reqDebugMsg = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_reqdebugmsg());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReqBody::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReqBody::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReqBody::GetClassData() const { return &_class_data_; }


void ReqBody::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReqBody*>(&to_msg);
  auto& from = static_cast<const ReqBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ReqBody)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.configlist_.MergeFrom(from._impl_.configlist_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_info(from._internal_info());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_province(from._internal_province());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_city(from._internal_city());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_mutable_queryuinpackageusagereq()->::QueryUinPackageUsageReq::MergeFrom(
          from._internal_queryuinpackageusagereq());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.reqdebugmsg_ = from._impl_.reqdebugmsg_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReqBody::CopyFrom(const ReqBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReqBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqBody::IsInitialized() const {
  return true;
}

void ReqBody::InternalSwap(ReqBody* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.configlist_.InternalSwap(&other->_impl_.configlist_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.info_, lhs_arena,
      &other->_impl_.info_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.province_, lhs_arena,
      &other->_impl_.province_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.city_, lhs_arena,
      &other->_impl_.city_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqBody, _impl_.reqdebugmsg_)
      + sizeof(ReqBody::_impl_.reqdebugmsg_)
      - PROTOBUF_FIELD_OFFSET(ReqBody, _impl_.queryuinpackageusagereq_)>(
          reinterpret_cast<char*>(&_impl_.queryuinpackageusagereq_),
          reinterpret_cast<char*>(&other->_impl_.queryuinpackageusagereq_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqBody::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Oidb0x769_2eproto_getter, &descriptor_table_Oidb0x769_2eproto_once,
      file_level_metadata_Oidb0x769_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ConfigSeq*
Arena::CreateMaybeMessage< ::ConfigSeq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ConfigSeq >(arena);
}
template<> PROTOBUF_NOINLINE ::QueryUinPackageUsageReq*
Arena::CreateMaybeMessage< ::QueryUinPackageUsageReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::QueryUinPackageUsageReq >(arena);
}
template<> PROTOBUF_NOINLINE ::ReqBody*
Arena::CreateMaybeMessage< ::ReqBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ReqBody >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
